# 04a_analysing_filtered_tweets-allwaves.R
# script to analyse filtered tweets from the entire panel during wave 01 [Sep 06 - Oct 10]
# for each of the available categories
# NL, 10/10/18
# NL, 13/10/18 
# NL, 30/10/18    updated for wave 02
# NL, 05/11/18    updated for wave 03
# NL, 05/11/18    updated for wave 04
# NL, 05/11/18    updated for wave 05
# NL, 06/11/18    updated for wave 06
# NL, 15/01/19    big update changing functionality to drop the wave-concept and analyse 
#                 all data in one go for the whole timeframe of interest, 
#                 aka 00_analysing_filtered_tweets.R
# NL, 25/01/19    adapting script for ctrl panel data, aka:
#                 04a_analysing_filtered_tweets-allwaves.R

library(dplyr)

DATA_PATH <- "~/Dropbox/PhD/midterms_paper/tweets/control_panel/data/"


# TO DO:
# - read in all the data that was output from the previous "analysing_filtered_tweets_" scripts
# - concatenate the existing csvs
# - output the new csvs
# - make everything in this new script replicable

# DATA IN
# these were generated by running analysing_filtered_tweets script for each of the waves.
# hence, all waves' file structures must be iterated through to recursively read in
# these files:

# 1 - to train classifiers with. voting ground truth data
# imvoting.csv
# or, more likely: imvoting.csv

# 2 - all tweets that fit inclusion criteria for the relevant topics
# trump_mention_tweets.csv
# kavanaugh_mention_tweets.csv
# republicans_mention_tweets.csv
# democrats_mention_tweets.csv
# midterms_mention_tweets.csv

# 3 - tweets which feature relevant hashtags, and the number of times they occur in the data
# dem_hashtag_tweets.csv
# rep_hashtag_tweets.csv
# all_hashtags_frequencies.csv

# 4 - no idea what this will be, but let's give it a go
# panel_members_relevant_mention_counts_waveXX.csv

imvoting_df <- NULL
trump_mentions_df <- NULL
kavanaugh_mentions_df <- NULL
midterms_mentions_df <- NULL
democrats_mentions_df <- NULL
republican_mentions_df <- NULL
dem_hashtag_tweets_df <- NULL
rep_hashtag_tweets_df <- NULL
all_hashtags_frequencies_df <- NULL

for(i in 1:6){
  
  # voting
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/imvoting.csv"), 
                      colClasses = "character"
                      ) %>% distinct(
    status_id, .keep_all = T
  )
  
  imvoting_df <- rbind(imvoting_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # trump
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/trump.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  )
  
  trump_mentions_df <- rbind(trump_mentions_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # kavanaugh
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/kavanaugh.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  kavanaugh_mentions_df <- rbind(kavanaugh_mentions_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # midterms
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/midterms.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  midterms_mentions_df <- rbind(midterms_mentions_df, pos1_df)  %>% distinct(
    status_id, .keep_all = T
  )
  
  # democrats
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/democrats.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  democrats_mentions_df <- rbind(democrats_mentions_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # republicans
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/republicans.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  republican_mentions_df <- rbind(republican_mentions_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # dem_hashtag_tweets
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/dems_hashtags.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  dem_hashtag_tweets_df <- rbind(dem_hashtag_tweets_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
  # rep_hashtag_tweets
  pos1_df <- read.csv(paste0(DATA_PATH, "wave_0", i, "_data/reps_hashtags.csv"), colClasses = "character") %>% distinct(
    status_id, .keep_all = T
  ) 
  
  rep_hashtag_tweets_df <- rbind(rep_hashtag_tweets_df, pos1_df) %>% distinct(
    status_id, .keep_all = T
  )
  
}

# write out

if(!dir.exists(paste0(DATA_PATH, "wave_everything_data"))){
  dir.create(paste0(DATA_PATH, "wave_everything_data"))
}

write.csv(imvoting_df, paste0(DATA_PATH, "wave_everything_data/imvoting.csv"))
write.csv(trump_mentions_df, paste0(DATA_PATH, "wave_everything_data/trump_mention_tweets.csv"))
write.csv(kavanaugh_mentions_df, paste0(DATA_PATH, "wave_everything_data/kavanaugh_mention_tweets.csv"))
write.csv(midterms_mentions_df, paste0(DATA_PATH, "wave_everything_data/midterms_mention_tweets.csv"))
write.csv(democrats_mentions_df, paste0(DATA_PATH, "wave_everything_data/democrats_mention_tweets.csv"))
write.csv(republican_mentions_df, paste0(DATA_PATH, "wave_everything_data/republicans_mention_tweets.csv"))
write.csv(dem_hashtag_tweets_df, paste0(DATA_PATH, "wave_everything_data/dem_hashtag_tweets.csv"))
write.csv(rep_hashtag_tweets_df, paste0(DATA_PATH, "wave_everything_data/rep_hashtag_tweets.csv"))
